class Solution:
    """
    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Find the letter that was added in t.

    Example:

    Input:
    s = "abcd"
    t = "abcde"

    Output:
    e

    Explanation:
    'e' is the letter that was added.
    """

    def findTheDifference(self, s: str, t: str) -> str:
        d = {}
        for i in s:
            if d.get(i):
                d[i] += 1
            else:
                d[i] = 1
        for i in t:
            if d.get(i):
                if d[i] == 1:
                    d.pop(i)
                else:
                    d[i] -= 1
            else:
                return i
